# ~/.config/zsh/aliases.zsh

alias gad='git add'
alias gcm='git commit'
alias gca='git commit --amend'
alias gcan='git commit --amend --no-edit'
alias gph='git push'
alias gpf='git push --force'
alias gplr='git pull -r'
alias gpln='git pull --no-rebase'
alias gre='git rebase'
alias gri='git rebase -i'
alias gbra='git branch -a'
alias gbr='git branch'
alias gsw='git switch'
alias gst='git status -sb'
alias glg='git log --graph --decorate --pretty=oneline --abbrev-commit'
alias glgl='git log --pretty=format:"%C(yellow)%h %C(blue)%ad %C(green)%an%n%Creset%s%n%n%b" --date=short --name-status'
alias gdf='git diff'
alias gdfs='git diff --staged'

alias ll='eza --header --long --group --git -Alh --sort=name'
alias l='eza -1'
alias ls='eza -Ah'
alias tree='eza -T'
alias cat='bat --style plain --paging never --theme OneHalfDark'
alias bat='bat --theme OneHalfDark'
alias cpy='xclip -selection clipboard'
alias ed='${EDITOR}'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

